### ISSUE TITLE
Upcheck sometimes blocked by Pruning

### ISSUE THREAD

**Issue by siladu** [Consensys/web3signer#891] opened 2023-08-29 07:49 UTC
...resulting in the service getting killed by k8s.

Reported by Yorick on Consensys Discord https://discord.com/channels/697535391594446898/725135157652226060/1145966681236193371

> It gets killed ... by k8s? 
> Normal   Killing    2m23s                  kubelet  Container web3signer failed liveness probe, will be restarted
So there's a liveness probe running, and when web3signer prunes, that's ... blocked? Prune can take over 2 mins

> 2 min 6 secs for manual prune. OK for now I will change web3signer: Prune every 6 hours, keep 100, prune on start. That should keep the pruning runs fast enough that the liveness probe block isn't an issue

```
       livenessProbe:
            httpGet:
              path: /upcheck
              port: http
            initialDelaySeconds: 900
            timeoutSeconds: 3
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
```
> So that sounds like after 90 secs of no /upcheck it gets killed. Prune takes longer than that and then it can never finish.
Which suggests /upcheck is blocked during prune, and it's usually so fast that's not seen - but Gnosis Chain with 10k validators and a restart of web3signer which restarts the 24 hour clock and well 😅
Prune on start and every 6 hours should help with this, even if /upcheck remains blocked
Particularly with that initialDelaySeconds, if it prunes on start it should always be able to finish, and then the runs after that will be faster

> 11 minutes ... maybe there are bits where it blocks and bits where it doesn't?
```
2023-08-29 07:21:40.445+00:00 | pool-3-thread-1 | INFO  | DBSlashingProtectionPruner | Pruning slashing protection database for 9879 validators
2023-08-29 07:32:54.310+00:00 | pool-3-thread-1 | INFO  | DBSlashingProtectionPruner | Pruning slashing protection database complete
```

> This is Gnosis2, much faster there
```
2023-08-29 07:39:26.056+00:00 | pool-3-thread-1 | INFO  | DBSlashingProtectionPruner | Pruning slashing protection database for 4971 validators
2023-08-29 07:40:23.991+00:00 | pool-3-thread-1 | INFO  | DBSlashingProtectionPruner | Pruning slashing protection database complete
```

**Comment by yorickdowne** [comment] 2023-08-29 13:38
It's possible the block happens during a SQL query, and lasts for as long as that single query lasts. Certainly pruning can go >90 secs and be successful:

```
2023-08-29 13:21:40.442+00:00 | pool-3-thread-1 | INFO  | DBSlashingProtectionPruner | Pruning slashing protection database for 9879 validators
2023-08-29 13:28:49.156+00:00 | pool-3-thread-1 | INFO  | DBSlashingProtectionPruner | Pruning slashing protection database complete
```

**Comment by gfukushima** [comment] 2023-09-04 07:30
Hi @yorickdowne, are there logs around that time W3S got killed? If you could share those that would be great. We're looking for possible `Thread blocked` logs or anything that looks like a possible error. We also found a small regression(which is already fixed in the main branch) where the upcheck was not returning or returning a 406 depending on the header sent by the request. It probably didn't affect you since this would normally result in the upcheck failing constantly.

**Comment by yorickdowne** [comment] 2023-09-04 11:37
Unfortunately I didn't capture those logs, and adding this environment to our promtail/Loki is somewhere in the "we will get to it ... eventually" backlog. Sorry!

**Closed** 2023-09-07 02:13 UTC
Labels: bug, TeamGroot, P3
